apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: config
    namespace: cloudflared
    files:
      - config.yaml
generatorOptions:
 disableNameSuffixHash: true
 
resources:
  - ns.yaml
  - daemon-set.yaml
  - external-secret.yaml
  