apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: cloudflared-config
    namespace: cloudflared
    files:
      - cloudflared-config.yaml

resources:
  - ns.yaml
  - cloudflared-config.yaml
  - daemon-set.yaml
  - external-secret.yaml