apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: veh
spec:
  forProvider:
    enabled: true
    email: vegard@vanillax.me
    firstName: Vegard
    lastName: Hagen
    username: veh
    realmIdRef:
      name: homelab