apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # - configmap.yaml
  # - deployment.yaml
  # - mcpo-deployment.yaml
  # - service.yaml
  # - pvc.yaml
  # - httproute.yaml
namespace: ollama-webui
