apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 1passwordconnect

resources:
  - namespace.yaml

helmCharts:
  - name: connect
    repo: https://1password.github.io/connect-helm-charts/
    version: 1.16.0 # Replace with the specific version you want to use
    releaseName: connect
    namespace: 1passwordconnect
    includeCRDs: true
    valuesInline:
      operator:
        create: true
        token:
          valueFrom:
            secretKeyRef:
              name: 1password-connect-secret
              key: operator-token
      connect:
        credentialsFrom:
          secretKeyRef:
            name: 1password-connect-secret
            key: credentials