apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - test-item.yaml

helmCharts:
  - name: connect
    repo: https://1password.github.io/connect-helm-charts
    releaseName: connect
    version: 1.12.1
    namespace: 1passwordconnect
    valuesFile: values.yaml