apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 1passwordconnect

resources:
  - namespace.yaml

helmCharts:
  - name: connect
    repo: https://1password.github.io/connect-helm-charts
    releaseName: connect
    version: 1.12.1
    namespace: 1passwordconnect
    valuesInline:
      connect:
        credentialsName: "1password-credentials"    # instead of existingSecret
        credentialsKey: "1password-credentials.json"  # instead of existingSecretKey
      operator:
        create: true
        token:
          name: "1password-operator-token"    # instead of existingSecret
          key: "token"                        # instead of existingSecretKey