connect:
  credentials:
    existingSecret: 1password-credentials
    existingSecretKey: 1password-credentials.json
  api:
    enabled: true
    resources:
      requests:
        memory: "150Mi"
        cpu: "100m"
      limits:
        memory: "300Mi"
        cpu: "200m"
  sync:
    enabled: true
    resources:
      requests:
        memory: "150Mi"
        cpu: "100m"
      limits:
        memory: "300Mi"
        cpu: "200m"

operator:
  create: true
  token:
    existingSecret: 1password-operator-token
    existingSecretKey: token
  resources:
    requests:
      memory: "150Mi"
      cpu: "100m"
    limits:
      memory: "300Mi"
      cpu: "200m"