connect:
  api:
    enabled: true
    resources:
      requests:
        memory: "150Mi"
        cpu: "100m"
      limits:
        memory: "300Mi"
        cpu: "200m"
  sync:
    enabled: true 
    resources:
      requests:
        memory: "150Mi"
        cpu: "100m"
      limits:
        memory: "300Mi"
        cpu: "200m"
  # Match the secret name from your README
  existingSecret: "1password-credentials"   
  existingSecretKey: "1password-credentials.json"

operator:
  create: true
  token:
    # Match the secret name from your README
    existingSecret: "1password-operator-token"    
    existingSecretKey: "token"
  resources:
    requests:
      memory: "150Mi"
      cpu: "100m"
    limits:
      memory: "300Mi"
      cpu: "200m"
  autoRestart: true
  pollingInterval: 300