apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxitok
  namespace: proxitok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxitok
  template:
    metadata:
      labels:
        app: proxitok
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: cache-volume
          emptyDir:
            medium: Memory
      initContainers:
        - name: init-cache
          image: busybox
          securityContext:
            runAsUser: 0
          command: ["/bin/sh", "-c"]
          args:
            - mkdir -p /cache/latte && 
              chown -R 65534:65534 /cache
          volumeMounts:
            - name: cache-volume
              mountPath: /cache
      containers:
        - name: main
          image: ghcr.io/pablouser1/proxitok@sha256:9300a54e10314e1fb8b3c2056705d6a931ce979d92793fd972c37ded446ece60
          volumeMounts:
            - name: cache-volume
              mountPath: /var/www/html/cache
          envFrom:
            - configMapRef:
                name: proxitok-configmap
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 600Mi
        - name: redis
          image: public.ecr.aws/docker/library/redis:7.4.1
          env:
            - name: REDIS_REPLICATION_MODE
              value: "master"
          command: ["redis-server", "--save", "50 1", "--loglevel", "notice"]
        - name: signer
          image: ghcr.io/pablouser1/signtok:master
          env:
            - name: PORT
              value: "8081"
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 512Mi