apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway-class.yaml
  - ns.yaml
  - cloudflare-api-token-sealed.yaml
  - cloudflare-issuer.yaml
  - gw-internal.yaml
  - gw-external.yaml
  - ext-gateway-service.yaml
  - int-gateway-service.yaml
