apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crowdsec

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - rbac.yaml
  - external-secret.yaml
  - service.yaml
  - httproute.yaml

commonLabels:
  app.kubernetes.io/name: crowdsec
  app.kubernetes.io/part-of: security 