apiVersion: apps/v1
kind: Deployment
metadata:
  name: perplexica-frontend-deployment
  namespace: perplexica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perplexica-frontend
  template:
    metadata:
      labels:
        app: perplexica-frontend
    spec:
      containers:
      - name: frontend-container
        image: mitchross09/perplexica-frontend:v1.0.6
        ports:
          - containerPort: 3000
        env:
          - name: NEXT_PUBLIC_API_URL
            value: https://perplexica.vanillax.me/api
          - name: NEXT_PUBLIC_WS_URL
            value: wss://perplexica.vanillax.me