apiVersion: v1
kind: ConfigMap
metadata:
  name: wyze-bridge-config
  namespace: wyze-bridge
data:
  WB_AUTH: "False"
  ON_DEMAND: "False"
  TZ: "America/Detroit"
  FILTER_NAMES: pet-cam
  FILTER_BLOCK: "True"
  # Add any other non-sensitive environment variables here
  # WB_IP: "your.node.ip.address"