apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-config
  namespace: paperless-ngx
data:
  PAPERLESS_TIME_ZONE: "America/New_York"
  PAPERLESS_OCR_LANGUAGE: "eng"
  PAPERLESS_CONSUMER_POLLING: "0"
  PAPERLESS_TASK_WORKERS: "2"
  PAPERLESS_THREADS_PER_WORKER: "2"
  PAPERLESS_WEBSERVER_WORKERS: "2"
  PAPERLESS_ENABLE_NLTK: "1"
  PAPERLESS_FILENAME_DATE_ORDER: "DMY"
  PAPERLESS_OCR_MODE: "skip"
  PAPERLESS_OCR_SKIP_ARCHIVE_FILE: "never"
  PAPERLESS_OCR_CLEAN: "clean"
  PAPERLESS_OCR_DESKEW: "true"
  PAPERLESS_OCR_ROTATE_PAGES: "true"
  PAPERLESS_OCR_OUTPUT_TYPE: "pdfa"
  PAPERLESS_CONSUMER_RECURSIVE: "true"
  PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
  PAPERLESS_REDIS: "redis://redis-master.redis.svc.cluster.local:6379"
  PAPERLESS_URL: "https://paperless.vanillax.me"
