apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng
  namespace: searxng
data:
  SEARXNG_DEBUG: "false"
  SEARXNG_URL: "https://search.vanillax.me"
  SEARXNG_PORT: "8080"  # Match with settings.yml
  SEARXNG_BIND_ADDRESS: "0.0.0.0"
  SEARXNG_BASE_URL: "https://search.vanillax.me"
  SEARXNG_INSTANCE_NAME: "searxng"