apiVersion: v1
kind: ConfigMap
metadata:
  name: tubearchivist-config
  namespace: tubearchivist
data:
  TZ: America/New_York
  ES_URL: http://archivist-es:9200
  REDIS_CON: redis://archivist-redis:6379
  TA_HOST: http://tubearchivist.talos:8000
---
apiVersion: v1
kind: Secret
metadata:
  name: tubearchivist-secrets
  namespace: tubearchivist
stringData:
  ELASTIC_PASSWORD: verysecret
  TA_USERNAME: vanillax
  TA_PASSWORD: verysecret
