kind: Deployment
apiVersion: apps/v1
metadata:
  name: tubearchivist
  namespace: tubearchivist
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tubearchivist
  template:
    metadata:
      labels:
        app: tubearchivist
    spec:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: tubearchivist
        image: bbilly1/tubearchivist:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8000
        envFrom:
        - configMapRef:
            name: tubearchivist-env
        env:
        - name: ES_URL
          value: "https://elastic:verysecret@archivist-es.tubearchivist.svc.cluster.local:9200"
        - name: ES_USERNAME
          value: "elastic"
        - name: REDIS_CON
          value: "redis://redis-external.redis-instance.svc.cluster.local:6379"
        - name: HOST_UID
          value: "1000"
        - name: HOST_GID
          value: "1000"
        - name: TA_HOST
          value: "http://tubearchivist.vanillax.me:8000"
        - name: PATH
          value: "/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        - name: ELASTIC_PASSWORD
          value: "verysecret"
        volumeMounts:
        - name: config
          mountPath: /config
        - name: youtube
          mountPath: /youtube
        - name: cache
          mountPath: /cache
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: tubearchivist-config-pvc
      - name: youtube
        persistentVolumeClaim:
          claimName: tubearchivist-media-pvc
      - name: cache
        persistentVolumeClaim:
          claimName: tubearchivist-cache-pvc
