defaultSettings:
  defaultDataPath: "/var/lib/longhorn"
preUpgradeChecker:
  jobEnabled: false
persistence:
  defaultClass: true
  defaultClassReplicaCount: 3
  defaultFsType: ext4
  reclaimPolicy: Delete
ingress:
  enabled: false