apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: system-upgrade-controller

resources:
  - ns.yaml
  - plans.yaml

helmCharts:
  - name: system-upgrade-controller
    repo: https://github.com/rancher/system-upgrade-controller.git
    version: v0.13.4
    releaseName: system-upgrade-controller
    namespace: system-upgrade-controller
    valuesFile: values.yaml