apiVersion: apps/v1
kind: Deployment
metadata:
  name: perplexica-backend-deployment
  namespace: perplexica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perplexica-backend
  template:
    metadata:
      labels:
        app: perplexica-backend
    spec:
      containers:
      - name: backend-container
        image: mitchross09/perplexica-backend:v1.0.1
        ports:
          - containerPort: 3001
        env:
          - name: SEARXNG_API_URL
            value: http://perplexica-searxng-service.perplexica.svc.cluster.local:8080
        volumeMounts:
          - mountPath: /home/perplexica/data
            name: backend-dbstore-volume
          - mountPath: /home/perplexica/uploads
            name: uploads-volume
          - mountPath: /home/perplexica/config.toml
            subPath: config.toml
            name: config-toml-configmap
      volumes:
        - name: backend-dbstore-volume
          persistentVolumeClaim:
            claimName: backend-dbstore-pvc
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: uploads-pvc
        - name: config-toml-configmap
          configMap:
            name: config-toml-configmap

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-toml-configmap
  namespace: perplexica
data:
  config.toml: |
    [GENERAL]
    PORT = 3001
    
    [SEARXNG]
    API_URL = "http://perplexica-searxng-service.perplexica.svc.cluster.local:8080"