apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudnative-pg
commonLabels:
  app.kubernetes.io/name: cloudnative-pg-cluster
  app.kubernetes.io/managed-by: argocd
resources:
  # - example-cluster.yaml
  - immich-postgresdb.yaml
  - paperless-postgresdb.yaml
  - externalsecret.yaml
  - pv.yaml
