apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

resources:
  - namespace.yaml
  - http-route.yaml
  - storage-class.yaml



helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    includeCRDs: true
    releaseName: longhorn
    version: 1.7.0
    namespace: longhorn-system
    valuesFile: values.yaml

configMapGenerator:
  - name: longhorn-values
    files:
      - values.yaml