apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system

resources:
  - namespace.yaml
  - longhorn-storage-class.yaml
  - longhorn-storage-class-safe.yaml
  - backupjob.yaml
  - http-route.yaml
  - node-disk-config.yaml

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io/
    releaseName: longhorn
    namespace: longhorn-system
    includeCRDs: true
    version: v1.7.2
    valuesFile: values.yaml