preUpgradeChecker:
  jobEnabled: false

persistence:
  defaultClass: true
  defaultFsType: ext4

defaultSettings:
  defaultDataPath: /mnt
  createDefaultDiskLabeledNodes: false
  defaultReplicaCount: 2
  replicaAutoBalance: least-effort
  storageOverProvisioningPercentage: 200
  storageMinimalAvailablePercentage: 25
  guaranteedEngineManagerCPU: 0.2
  guaranteedReplicaManagerCPU: 0.2

nodes:
  - name: vanillax-ai
    allowScheduling: true
    disks:
      disk-1:
        path: /mnt/PNY232323060701001C5
        allowScheduling: true
        storageReserved: 10Gi
        tags: ["ssd", "data"]
      disk-2:
        path: /mnt/PNY232323060701001C1
        allowScheduling: true
        storageReserved: 10Gi
        tags: ["ssd", "data"]
      disk-3:
        path: /mnt/PNY232323060701001BD
        allowScheduling: true
        storageReserved: 10Gi
        tags: ["ssd", "backup"]
      disk-4:
        path: /mnt/PNY232323060701001C6
        allowScheduling: true
        storageReserved: 10Gi
        tags: ["ssd", "backup"]