apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - cloudflare-external-secret.yaml
  - cluster-issuer.yaml
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.18.2
    releaseName: cert-manager
    valuesFile: values.yaml
    includeCRDs: true
