image:
  repository: ghcr.io/home-assistant/home-assistant
  tag: 2025.7.1
  pullPolicy: IfNotPresent
env:
  TZ: "America/New_York"
service:
  main:
    ports:
      http:
        port: 8123
hostNetwork: true
securityContext:
  privileged: true
  allowPrivilegeEscalation: true
persistence:
  config:
    enabled: true
    storageClass: "local-path"
    size: 10Gi
    accessMode: ReadWriteOnce
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    memory: 4Gi
    cpu: 2000m
additionalVolumes:
  - name: config-file
    configMap:
      name: home-assistant-config
additionalVolumeMounts:
  - name: config-file
    mountPath: /config/configuration.yaml
    subPath: configuration.yaml
  - name: config-file
    mountPath: /config/automations.yaml
    subPath: automations.yaml
  - name: config-file
    mountPath: /config/scripts.yaml
    subPath: scripts.yaml
  - name: config-file
    mountPath: /config/scenes.yaml
    subPath: scenes.yaml
  - name: localtime
    mountPath: /etc/localtime
    readOnly: true
    hostPath:
      path: /etc/localtime
      type: File
