apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - namespace.yaml
  - pvc.yaml
  - mqtt/mqtt.yaml
  - pvc-config.yaml
  - service.yaml
  - httproute.yaml
namespace: frigate
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: frigate-configmap
    files:
      - config.yaml
