envs:
  targetNamespace:
  resourcesVisible: "True"
  operatorApiUrl: "http://zalando-postgres-postgres-operator.cnpg-zalando.svc.cluster.local:8080"
ingress:
  enabled: true  # Disable the built-in ingress as we're using HTTPRoute
service:
  create: false


