apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudnative-pg
resources:
  - operator
  - clusters/default
helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.github.io/charts
    version: 0.20.1
    releaseName: cloudnative-pg
    namespace: cloudnative-pg
    includeCRDs: true
